completing view single article
althrntn/alice-nc-news pull request #4
Opened 2022-09-27 14:48 UTC by althrntn

2022-09-27 14:53 UTC, popatre requested changes

2022-09-27 14:53 UTC, popatre commented on src/components/SingleArticle.jsx
> +    })
This is missing the dependency array - its currently constantly doing this request

2022-09-27 14:53 UTC, popatre commented on src/components/SingleArticle.jsx
> +    })
Its also just missing some error handling for if I got to an id that isnt there. 
At the moment, it just shows a constant loading state

2022-09-28 08:18 UTC, HMelesi approved these changes
Looks good Alice!

I was just having a look around your app generally and you're getting some warnings about keys in the console. Just needs fixing at some point. Also some weird stuff happens when you resize the screen! Styling comes on a later ticket so don't worry about it now, but just wanted to point out while I noticed :)

2022-09-28 08:18 UTC, HMelesi commented on src/components/ArticleCard.jsx
> +    <button className="article_button" onClick={(e)=>{navigate(`/articles/${article.article_id}`)}}>Read in full</button></li>)
You don't need the e event parameter here as you don't use it, I'd just leave it empty.

2022-09-28 08:40 UTC, merged